import { Listing } from './types';

export const KARACHI_AREAS = [
  'Gulshan-e-Iqbal', 'PECHS', 'Gulistan-e-Johar', 'North Nazimabad',
  'Nazimabad', 'Clifton', 'Defence (DHA)', 'Saddar', 'Malir', 'Korangi',
  'Landhi', 'FB Area', 'Liaquatabad', 'Orangi Town', 'Surjani Town',
  'Scheme 33', 'Buffer Zone', 'Shah Faisal Colony', 'Baldia', 'Lyari'
];

export const UNIVERSITIES = [
  'FAST-NU', 'IBA', 'NED', 'Karachi University', 
  'Dow Medical', 'Aga Khan', 'SZABIST', 'Indus Valley', 'PAF-KIET', 
  'Bahria University', 'Sir Syed', 'Ziauddin', 'DHA Suffa', 'Other'
];

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Boys Hostel near NED University',
    type: 'Hostel',
    area: 'Gulshan-e-Iqbal',
    university: 'NED',
    rent: 12000,
    securityDeposit: 5000,
    gender: 'Boys',
    mealsIncluded: true,
    utilities: 'Yes',
    seatsAvailable: 4,
    totalRoommates: 40,
    wifi: true,
    ac: false,
    description: 'Neat and clean rooms. Walking distance from NED and KU.',
    contactName: 'Ahmed Khan',
    whatsappNumber: '+923001234567',
    moveInDate: '2024-06-01',
    ownerId: 'system',
    createdAt: Date.now() - 100000,
  },
  {
    id: '2',
    title: 'Girls Hostel with 3 Meals near KU',
    type: 'Hostel',
    area: 'Gulistan-e-Johar',
    university: 'Karachi University',
    rent: 15000,
    securityDeposit: 10000,
    gender: 'Girls',
    mealsIncluded: true,
    utilities: 'Yes',
    seatsAvailable: 2,
    totalRoommates: 20,
    wifi: true,
    ac: true,
    description: 'Safe and secure environment for girls. CCTV monitored.',
    contactName: 'Mrs. Fatima',
    whatsappNumber: '+923119876543',
    moveInDate: '2024-05-15',
    ownerId: 'system',
    createdAt: Date.now() - 200000,
  },
  {
    id: '3',
    title: 'Sharing Flat Seat near FAST',
    type: 'Sharing Flat',
    area: 'Gulshan-e-Iqbal',
    university: 'FAST-NU',
    rent: 8500,
    securityDeposit: 8500,
    gender: 'Boys',
    mealsIncluded: false,
    utilities: 'Partial',
    seatsAvailable: 1,
    totalRoommates: 3,
    wifi: true,
    ac: false,
    description: 'Flat sharing with 2 other FASTians. Close to campus.',
    contactName: 'Ali Raza',
    whatsappNumber: '+923011112222',
    moveInDate: '2024-05-20',
    ownerId: 'system',
    createdAt: Date.now() - 300000,
  },
  {
    id: '4',
    title: 'Modern sharing flat near IBA',
    type: 'Sharing Flat',
    area: 'PECHS',
    university: 'IBA',
    rent: 18000,
    securityDeposit: 30000,
    gender: 'Any',
    mealsIncluded: false,
    utilities: 'No',
    seatsAvailable: 2,
    totalRoommates: 4,
    wifi: true,
    ac: true,
    description: 'Upscale flat in PECHS Block 6. Walking distance to IBA city campus.',
    contactName: 'Zubair',
    whatsappNumber: '+923455556666',
    moveInDate: '2024-06-10',
    ownerId: 'system',
    createdAt: Date.now() - 400000,
  },
  {
    id: '5',
    title: 'Cheap Sharing for PMC/Dow students',
    type: 'Sharing Flat',
    area: 'Saddar',
    university: 'Dow Medical',
    rent: 6500,
    securityDeposit: 5000,
    gender: 'Boys',
    mealsIncluded: false,
    utilities: 'Partial',
    seatsAvailable: 3,
    totalRoommates: 5,
    wifi: true,
    ac: false,
    description: 'Basic accommodation near Civil Hospital/Dow.',
    contactName: 'Kashif',
    whatsappNumber: '+923334445555',
    moveInDate: '2024-05-01',
    ownerId: 'system',
    createdAt: Date.now() - 500000,
  },
  {
    id: '6',
    title: 'Single Room in North Nazimabad',
    type: 'Single Room',
    area: 'North Nazimabad',
    university: 'Sir Syed',
    rent: 20000,
    securityDeposit: 20000,
    gender: 'Any',
    mealsIncluded: false,
    utilities: 'Yes',
    seatsAvailable: 1,
    totalRoommates: 0,
    wifi: true,
    ac: true,
    description: 'Independent annex room with separate entrance.',
    contactName: 'Uncle Mansoor',
    whatsappNumber: '+923023334444',
    moveInDate: '2024-06-01',
    ownerId: 'system',
    createdAt: Date.now() - 600000,
  },
  {
    id: '7',
    title: 'Economical Single Room',
    type: 'Single Room',
    area: 'Gulshan-e-Iqbal',
    university: 'Sir Syed',
    rent: 14000,
    securityDeposit: 14000,
    gender: 'Boys',
    mealsIncluded: false,
    utilities: 'Partial',
    seatsAvailable: 1,
    totalRoommates: 2,
    wifi: true,
    ac: false,
    description: 'Spacious room in a 3-bed flat. Two students in other rooms.',
    contactName: 'Bilal',
    whatsappNumber: '+923156667777',
    moveInDate: '2024-05-15',
    ownerId: 'system',
    createdAt: Date.now() - 700000,
  },
  {
    id: '8',
    title: 'Family Apartment near SZABIST',
    type: 'Full Apartment',
    area: 'Clifton',
    university: 'SZABIST',
    rent: 25000,
    securityDeposit: 50000,
    gender: 'Any',
    mealsIncluded: false,
    utilities: 'No',
    seatsAvailable: 1,
    totalRoommates: 0,
    wifi: false,
    ac: true,
    description: '2-bed apartment, ideal for students who want to live with family or group.',
    contactName: 'Imran Sahab',
    whatsappNumber: '+923000001111',
    moveInDate: '2024-07-01',
    ownerId: 'system',
    createdAt: Date.now() - 800000,
  },
  {
    id: '9',
    title: 'Aga Khan Student Sharing in FB Area',
    type: 'Sharing Flat',
    area: 'FB Area',
    university: 'Aga Khan',
    rent: 11000,
    securityDeposit: 11000,
    gender: 'Girls',
    mealsIncluded: false,
    utilities: 'Yes',
    seatsAvailable: 2,
    totalRoommates: 3,
    wifi: true,
    ac: false,
    description: 'Safe neighborhood, close to AKU and Liaquat National.',
    contactName: 'Saima',
    whatsappNumber: '+923005558888',
    moveInDate: '2024-06-01',
    ownerId: 'system',
    createdAt: Date.now() - 900000,
  },
  {
    id: '10',
    title: 'Indus Valley (IVS) Flatmate needed',
    type: 'Sharing Flat',
    area: 'Clifton',
    university: 'Indus Valley',
    rent: 22000,
    securityDeposit: 22000,
    gender: 'Any',
    mealsIncluded: false,
    utilities: 'No',
    seatsAvailable: 1,
    totalRoommates: 2,
    wifi: true,
    ac: true,
    description: 'Looking for a creative flatmate. Walking distance to IVS.',
    contactName: 'Daniyal',
    whatsappNumber: '+923214443333',
    moveInDate: '2024-06-15',
    ownerId: 'system',
    createdAt: Date.now() - 1000000,
  },
  {
    id: '11',
    title: 'Bahria Uni Boys Hostel',
    type: 'Hostel',
    area: 'Defence (DHA)',
    university: 'Bahria University',
    rent: 14500,
    securityDeposit: 5000,
    gender: 'Boys',
    mealsIncluded: true,
    utilities: 'Yes',
    seatsAvailable: 5,
    totalRoommates: 35,
    wifi: true,
    ac: false,
    description: 'Professional management. Near Bahria and Air University.',
    contactName: 'Manager Aslam',
    whatsappNumber: '+923347776666',
    moveInDate: '2024-05-30',
    ownerId: 'system',
    createdAt: Date.now() - 1100000,
  },
  {
    id: '12',
    title: 'Private Annex near Sir Syed',
    type: 'Single Room',
    area: 'North Nazimabad',
    university: 'Sir Syed',
    rent: 18500,
    securityDeposit: 37000,
    gender: 'Any',
    mealsIncluded: false,
    utilities: 'Yes',
    seatsAvailable: 1,
    totalRoommates: 0,
    wifi: true,
    ac: false,
    description: 'Completely private with attach bath and small kitchen.',
    contactName: 'Mrs. Perveen',
    whatsappNumber: '+923019998888',
    moveInDate: '2024-06-01',
    ownerId: 'system',
    createdAt: Date.now() - 1200000,
  },
  {
    id: '13',
    title: 'Sharing flat in Scheme 33',
    type: 'Sharing Flat',
    area: 'Scheme 33',
    university: 'Karachi University',
    rent: 7500,
    securityDeposit: 7500,
    gender: 'Boys',
    mealsIncluded: false,
    utilities: 'Partial',
    seatsAvailable: 2,
    totalRoommates: 4,
    wifi: true,
    ac: false,
    description: 'New building, very clean. Shuttle service to KU nearby.',
    contactName: 'Mustafa',
    whatsappNumber: '+923450001111',
    moveInDate: '2024-05-15',
    ownerId: 'system',
    createdAt: Date.now() - 1300000,
  },
  {
    id: '14',
    title: 'Executive Girls Hostel - North Nazimabad',
    type: 'Hostel',
    area: 'North Nazimabad',
    university: 'Ziauddin',
    rent: 20000,
    securityDeposit: 15000,
    gender: 'Girls',
    mealsIncluded: true,
    utilities: 'Yes',
    seatsAvailable: 2,
    totalRoommates: 15,
    wifi: true,
    ac: true,
    description: 'Premium facilities for medical students. Near Ziauddin hospital.',
    contactName: 'Hostel Warden',
    whatsappNumber: '+923126665555',
    moveInDate: '2024-06-01',
    ownerId: 'system',
    createdAt: Date.now() - 1400000,
  },
  {
    id: '15',
    title: 'Malir Cantt Student Accommodation',
    type: 'Sharing Flat',
    area: 'Malir',
    university: 'Karachi University',
    rent: 9000,
    securityDeposit: 9000,
    gender: 'Boys',
    mealsIncluded: false,
    utilities: 'Yes',
    seatsAvailable: 1,
    totalRoommates: 3,
    wifi: true,
    ac: false,
    description: 'Inside a secure society. Peacefull for studies.',
    contactName: 'Sufyan',
    whatsappNumber: '+923002223333',
    moveInDate: '2024-07-01',
    ownerId: 'system',
    createdAt: Date.now() - 1500000,
  },
  {
    id: '16',
    title: 'Korangi sharing near PAF-KIET',
    type: 'Sharing Flat',
    area: 'Korangi',
    university: 'PAF-KIET',
    rent: 8000,
    securityDeposit: 5000,
    gender: 'Boys',
    mealsIncluded: false,
    utilities: 'No',
    seatsAvailable: 3,
    totalRoommates: 6,
    wifi: true,
    ac: false,
    description: 'Budget friendly for PAF-KIET students.',
    contactName: 'Noman',
    whatsappNumber: '+923331112222',
    moveInDate: '2024-06-01',
    ownerId: 'system',
    createdAt: Date.now() - 1600000,
  },
  {
    id: '17',
    title: 'Nazimabad Block 4 Single Unit',
    type: 'Full Apartment',
    area: 'Nazimabad',
    university: 'Sir Syed',
    rent: 30000,
    securityDeposit: 60000,
    gender: 'Any',
    mealsIncluded: false,
    utilities: 'No',
    seatsAvailable: 1,
    totalRoommates: 0,
    wifi: false,
    ac: false,
    description: 'Complete upper portion. Best for a group of 4-5 friends.',
    contactName: 'Riaz Sahab',
    whatsappNumber: '+923057778888',
    moveInDate: '2024-06-15',
    ownerId: 'system',
    createdAt: Date.now() - 1700000,
  },
  {
    id: '18',
    title: 'Johar Block 15 Boys Sharing',
    type: 'Sharing Flat',
    area: 'Gulistan-e-Johar',
    university: 'Karachi University',
    rent: 10000,
    securityDeposit: 10000,
    gender: 'Boys',
    mealsIncluded: false,
    utilities: 'Yes',
    seatsAvailable: 2,
    totalRoommates: 4,
    wifi: true,
    ac: false,
    description: 'Very close to Continental bakery side. Easy transport to KU.',
    contactName: 'Taha',
    whatsappNumber: '+923168889999',
    moveInDate: '2024-06-01',
    ownerId: 'system',
    createdAt: Date.now() - 1800000,
  }
];

export const SYSTEM_PROMPT = `You are KamraFind Assistant, a helpful room-finding guide for university students in Karachi, Pakistan.

Your personality: friendly, honest, big-brother energy. You speak in Roman Urdu by default but switch to English if student does.

Your job:
1. Ask smart questions to understand what the student needs
2. Based on their answers, recommend the best matching listings from the data you receive
3. Give practical Karachi-specific advice
4. Warn about common rental scams in Karachi
5. Tell students what questions to ask before renting

You know Karachi well:
- Gulshan, Johar, North Nazimabad = affordable, student-friendly
- DHA, Clifton = expensive, but some sharing options exist
- Areas near NED: FB Area, North Nazimabad, Nazimabad
- Areas near FAST Gulshan: Gulshan blocks 1-7, Johar
- Areas near Karachi Uni: Gulshan, Johar, Scheme 33
- Areas near IBA: Gulshan, PECHS, Saddar
- Areas near Dow: Baba-e-Urdu Road, Saddar, Lyari

Common scams to warn about:
- Fake listings asking for advance without showing room
- Landlords who take deposit and disappear
- Hidden extra charges not mentioned upfront
- Substandard condition hidden in photos

Questions to suggest students ask landlord:
- Bijli ka meter alag hai ya shared?
- Koi extra charges hain? (gas, pani, guard)
- Agreement hoga ya nahi?
- Guests aane ki permission hai?
- Khana kon banata hai? (if meals included)
- Kitne logo ka ghar hai total?

After understanding needs, output a JSON block at the end:
FILTERS_JSON:
{type, area, maxBudget, university, gender, meals}`;

export const formatPrice = (p: number | string | undefined | null): string => {
  if (p === undefined || p === null) return '0';
  const num = Number(p);
  if (isNaN(num)) return '0';
  if (num >= 1e12) {
    return `${(num / 1e12).toFixed(1).replace(/\.0$/, '')}T`;
  }
  if (num >= 1e9) {
    return `${(num / 1e9).toFixed(1).replace(/\.0$/, '')}B`;
  }
  if (num >= 1e6) {
    return `${(num / 1e6).toFixed(1).replace(/\.0$/, '')}M`;
  }
  return num.toLocaleString();
};
